// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZK3iyOmmAPHtO6lME7uiL_cidbNZmSBg',
    appId: '1:249224037321:web:2a055cff2b522afb6ade18',
    messagingSenderId: '249224037321',
    projectId: 'gramshikshika',
    authDomain: 'gramshikshika.firebaseapp.com',
    storageBucket: 'gramshikshika.firebasestorage.app',
    measurementId: 'G-6Z744DYJ0L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQam34Ba5vVO8FII-p0QdkU_5PUlVBLWQ',
    appId: '1:249224037321:android:c4131a9e801305e26ade18',
    messagingSenderId: '249224037321',
    projectId: 'gramshikshika',
    storageBucket: 'gramshikshika.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF5q1X0t07wXm5gP5t55gbS_4vzp8hUf4',
    appId: '1:249224037321:ios:663da8ac8d1706af6ade18',
    messagingSenderId: '249224037321',
    projectId: 'gramshikshika',
    storageBucket: 'gramshikshika.firebasestorage.app',
    iosBundleId: 'com.example.gramshikshika',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF5q1X0t07wXm5gP5t55gbS_4vzp8hUf4',
    appId: '1:249224037321:ios:663da8ac8d1706af6ade18',
    messagingSenderId: '249224037321',
    projectId: 'gramshikshika',
    storageBucket: 'gramshikshika.firebasestorage.app',
    iosBundleId: 'com.example.gramshikshika',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZK3iyOmmAPHtO6lME7uiL_cidbNZmSBg',
    appId: '1:249224037321:web:b76922fd15d586f66ade18',
    messagingSenderId: '249224037321',
    projectId: 'gramshikshika',
    authDomain: 'gramshikshika.firebaseapp.com',
    storageBucket: 'gramshikshika.firebasestorage.app',
    measurementId: 'G-WB8L064Q0E',
  );
}
